const data = [
  {
    id: 1,
    name: "John",
    age: 30,
    salary: 5000,
    Designation: "Manager",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 2,
    name: "Peter",
    age: 25,
    salary: 3000,
    Designation: "Developer",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 3,
    name: "Amy",
    age: 22,
    salary: 2000,
    Designation: "Developer",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 4,
    name: "Hannah",
    age: 35,
    salary: 5500,
    Designation: "Manager",
    Department: "HR",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 5,
    name: "Michael",
    age: 27,
    salary: 4000,
    Designation: "Developer",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 6,
    name: "Rose",
    age: 21,
    salary: 2500,
    Designation: "Developer",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 7,
    name: "Nancy",
    age: 32,
    salary: 6000,
    Designation: "Manager",
    Department: "HR",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 8,
    name: "Robert",
    age: 43,
    salary: 7500,
    Designation: "Manager",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
  {
    id: 9,
    name: "Chris",
    age: 29,
    salary: 3000,
    Designation: "Developer",
    Department: "IT",
    image: "https://i.pravatar.cc/200",
  },
];

export default data;
